Спринт 3
LemonGrace/react-burger pull request #5
Opened 2022-05-31 11:59 UTC by LemonGrace

Работала с другого ноутбука, где забыла сначала поменять пользователя(

2022-06-01 18:12 UTC, grishbar requested changes
Большая работа проделана, круто работаешь с куки и с их обновленем, хорошо что хранишь токены в куки а не в локальном хранилище 👍.. Также мне понравилось, как обрабатываешь состояние форм, код там написан довольно лаконично. Есть несколько моментов, которые надо поправить для принятия работы:

- [ ] Обрати внимание на warning в консоли их все надо бы исправить Клик по ингредиенту и открытие деталей, не должно быть спрятано под 
- [ ] Если я не авторизован, и попытаюсь оформить заказ на бургер, меня перекидывает на страницу /login но после авторизации приложение падает, хотя ожидается, что меня перекинет обратно
- [ ] Не работают табы в ингредиентах (при клике на “Булки”, “Соусы”,  ингредиенты должны скроллится до соответствующей группы)
- [ ] После выхода из профиля, меня должно выкидывать на страницу авторизации
- [ ] Избавиться от дублирования AppHeader в app.jsx
- [ ] При открытии деталей ингредиента в модалке, все что находится сзади моталки не должно стираться и перерисовываться
- [ ] Перенести логику авторизации в экшен
- [ ] Избавиться от дублирования логики
- [ ] Перестать создавать одни компоненты внутри других
- [ ] Перенести action type в редьюсеры

2022-06-01 18:12 UTC, grishbar commented on src/components/app/app.jsx
> +                    </ProtectedRoute>
`надо исправить` 
детали ингредиента не должны быть защищеным роутом, туда должен быть доступ как у авторизированных пользователей, так и у неавторизрованных

2022-06-01 18:12 UTC, grishbar commented on src/components/app/app.jsx
> +                    </Route>
`надо исправить` 
Роуты /login и /register, /forgot-password и /reset-password не доступны авторизованным пользователям.

2022-06-01 18:12 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
>                      Оформить заказ
`надо исправить`
    [нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html)
    Пройдись пожалуйста по всему проекту и исправь везде эту проблему

2022-06-01 18:12 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +    const isAuth = !!getCookie('token');
`надо исправить` 
состояние авторизирован пользователь или нет надо бы хранить в redux, и везде пользоваться состоянием объекта из хранилища. Так как этот параметр будешь использовать в различных частях приложения, поэтому логично, что он должнен храниться в глобальном состоянии твоего приложения

2022-06-01 18:12 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                 //dispatch({type: SET_TYPE, modalType: "details"});
`можно лучше`
    комментарии которые не документируют дальнейший код (не говорят, что будет происходит в последующих строчках под ними) должны быть удалены

2022-06-01 18:12 UTC, grishbar commented on src/components/app/app.jsx
> +                        <AppHeader/>
`надо исправить` 
надо вынести AppHeader снаружи всех роутов, чтобы не дублировать его

2022-06-01 18:12 UTC, grishbar commented on src/components/ingredient-details/ingredient-details.jsx
> +    } else {
`надо исправить` 
else не нужен, если у тебя выше в if return

2022-06-01 18:12 UTC, grishbar commented on src/components/ingredient-details/ingredient-details.jsx
> +        const item = ingredients.find(item => item._id === id);
`можно лучше`
    Требуется называть переменные и функции так, как будто их будут читать совершенно незнакомые люди. Так, чтобы любой человек который будет видеть твою переменную смог примерно понять, что в ней находится. Побольше насчет корректного названия переменных можно почитать [здесь](https://thecode.media/variables/)
    item слишком абстрактное название переменной, такое недопустимо, сделай пожалуйста название переменной, которое более явно отражает, что в ней лежит

2022-06-01 18:12 UTC, grishbar commented on src/components/modal-overlay/modal-overlay.jsx
> +			}
`надо исправить` 
не надо вызвать несколько dispatch подряд рядом, если тебе нужно выполнить подобное действие, то это явный сигнал, что эти диспатчи должны быть вынесены в отдельный понятный action, также обрати внимание и в других местах, где так делаешь

2022-06-01 18:12 UTC, grishbar commented on src/components/modal/modal.jsx
>      }, [handleClose]);
`надо исправить` 
не надо дизейблить линтер без необходимости
Можешь спокойно добавить history в зависимости лишние перендеры взываться не будут, так как хук useHistory нам обещает, что всегда будет возвращать один и тот же экземпляр объекта. 
строка        // eslint-disable-next-line во первых создает пространство для багов в будущем, а во вторых, дает лишнюю смысловую нагрузку на код

2022-06-01 18:12 UTC, grishbar commented on src/components/profile-nav/profile-nav.jsx
> +    let logoutUser = useCallback(e => {
`надо исправить` 
это const

2022-06-01 18:12 UTC, grishbar commented on src/components/protected-route.jsx
> +    console.log(location)
`надо исправить` 
console.log в продакшен решении быть не должно

2022-06-01 18:12 UTC, grishbar commented on src/components/protected-route.jsx
> +    }
`надо исправить` 
Кажется, что вся эта вся логика должна быть в экшене, где мы получаем аксесс токен из кук если его нет, то обновляем при помощи рефреш токена, если и его нет, то редиректим на страницу авторизации, сохраняя в юрле страницу куда обратно вернуться после успешной авторизации

2022-06-01 18:12 UTC, grishbar commented on src/pages/forgot-password/forgot-password.jsx
> +    let reset = useCallback(
`надо исправить` 
кажется это const

2022-06-01 18:12 UTC, grishbar commented on src/pages/forgot-password/forgot-password.jsx
> +    }
`можно лучше` 
в идеале тут бы лоадер показывать

2022-06-01 18:12 UTC, grishbar commented on src/pages/home/home.jsx
> +    }
`надо исправить`
```
if (itemsRequest && itemsFailed) {
        return (<></>)
}

return (<main ... </main>)
```

2022-06-01 18:12 UTC, grishbar commented on src/pages/home/home.jsx
> +    if (!itemsRequest && !itemsFailed) {
`надо исправить` 
на самом деле не очень понятно, что значит itemsRequest, будет лучше если она будет называться ingredientsFetching или isIngredientsLoading, и лучше вобще везде избавиться от items в названии, так как это слишком абстрактное имя переменное, которое может содержать все что угодно

2022-06-01 18:12 UTC, grishbar commented on src/pages/login/login.jsx
> +
`надо исправить` 
isAuth надо перенести в хранилище, но тем не менее, тут эта переменная должна была создаваться при помощи useState, так как React сможет лучше оценивать когда ему надо перерисовывать компонент зависящие от этой пропсы, а когда нет

2022-06-01 18:12 UTC, grishbar commented on src/pages/login/login.jsx
> +    }
`надо исправить` 
нужно убрать логику isAuth отсюда она должна храниться только в protectedRoute, незачем ее дублировать

2022-06-01 18:12 UTC, grishbar commented on src/pages/profile/profile.jsx
> +                    </div>
`надо исправить` 
это у тебя отдельный компонент, незачем держать его внутри этого компонента. Так как сейчас он у тебя будет пересчитываться на каждый ререндер ProfilePage и во вторых такой компонент становится читать очень тяжело, не обязательно выносить в отдельный файл, можешь просто ниже объявить эту функцию

2022-06-01 18:12 UTC, grishbar commented on src/pages/registration/registration.jsx
> +        return (
`надо исправить` 
пройдись пожалуйста по всем компонентам и избавься пожлайста везде от этой логики с проверкой аутентификации, эта логика должна храниться только в ProtectedRoute

2022-06-01 18:12 UTC, grishbar commented on src/services/actions/auth.js
> +export const LOGIN_ERROR = 'LOGIN_ERROR';
`надо исправить` 
action type должны храниться в редьюсерах. В целом можешь хранить их в любом месте, но главное, чтобы для всех action type  это было одно место а actionCreatorов у тебя для всех редьюсеров не будет, и общепринято хранить action type рядом с редьюсером

2022-06-01 18:12 UTC, grishbar commented on src/services/reducers/auth.js
> +        }
`надо исправить` 
кажется userInfoRequest и updateRequest одно и тоже надо бы объединить и их бы переименовать тут смысл в том, что это булевая переменная которая отвечает за то грузятся сейчас юзер данные или нет соответственно она так и должна называться, что то типа: isUserLoading

2022-06-01 18:12 UTC, grishbar commented on src/services/reducers/auth.js
> +            return { ...state, user: action.user, userInfoRequest: false, userInfoFailed: false,
`надо исправить` 
не надо деструктурировать state в возвращаемый объект без необходимости

2022-06-01 18:12 UTC, grishbar commented on src/services/reducers/auth.js
> +    },
`надо исправить` 
хранить объекты в redux это антипаттерн, старайся так не делать никогда, вот тут есть [хорошая статья](https://medium.com/collaborne-engineering/why-not-to-store-objects-in-redux-7f41243020fc) про это

2022-06-01 18:12 UTC, grishbar commented on src/services/reducers/auth.js
> +        }
`надо исправить`
    При ошибке в запросе надо возвращать - initialState и logoutFailed: true , так как не хочется держать в хранилище потенциально невалидные данные
    также пройдись пожалуйста по остальным местам, где так делаешь и поправь пожалуйста

2022-06-02 08:15 UTC, LemonGrace commented on src/components/app/app.jsx
> +                    </ProtectedRoute>
Здравствуйте! В ТЗ написано, что должны быть и это подтвердил наставник в беседе Slack. Какой вариант правильный?
![photo_2022-06-02_11-13-57](https://user-images.githubusercontent.com/42918083/171585739-456e1d5f-6581-4e0b-b4ff-1eef403bcb38.jpg)

2022-06-02 14:16 UTC, grishbar commented on src/components/app/app.jsx
> +                    </ProtectedRoute>
Привет вот тут написаны все защищенные роуты в 6 пункте
```
Куда не может попасть неавторизованный пользователь:
- Маршрут /profile.
- Все вложенные в /profile маршруты.
Все остальные маршруты не защищены.
Куда не может попасть авторизованный пользователь:
- Маршруты /login и /register.
- Маршруты /forgot-password и /reset-password.
```
https://practicum.yandex.ru/learn/react/courses/36f94820-19c9-4dfb-beed-5c4858c587e2/sprints/9586/topics/f4914b23-ab6f-4362-aae4-e78a72093099/lessons/fdc72800-02ce-438c-8c16-effed1aa8268/

2022-06-02 14:17 UTC, grishbar commented on src/components/app/app.jsx
> +                    </ProtectedRoute>
так что детализация ингредиента не должна быть защищенным маршрутом

2022-06-02 14:20 UTC, LemonGrace commented on src/components/app/app.jsx
> +                    </ProtectedRoute>
А про какие тогда права идёт речь в пункте 7: "А если пользователь напрямую переходит по ссылке на маршрут конкретного ингредиента, то при наличии нужных прав у пользователя просто открывается отдельная страница." - я запуталась(

2022-06-02 14:24 UTC, grishbar commented on src/components/app/app.jsx
> +                    </ProtectedRoute>
справедливое замечание, сейчас уточню, и вернусь с ответом

2022-06-02 14:28 UTC, grishbar commented on src/components/app/app.jsx
> +                    </ProtectedRoute>
Да, страничка с детализацией ингредиента не должна быть защищенным роутом, то есть должна открываться для всех

2022-06-02 14:31 UTC, LemonGrace commented on src/components/app/app.jsx
> +                    </ProtectedRoute>
Поняла, спасибо!

2022-06-06 13:49 UTC, grishbar requested changes
Видно, что многое поправила, работа стала напорядок лучше, но все еще есть моменты, которые надо бы улучшить для принятия работы:

- [ ] Все еще много ворнингов в консоли, от них от всех нужно избавиться
- [ ] После разлогина нужно удалять куки пользователя, иначе разлогиниться не получается
- [ ] Указать propTypes у всех компонентов
- [ ] Сломалась кнопка “Оформить заказ”
- [ ] Надо возвращать initialState при ошибке в запросе
<img width="1512" alt="Screen Shot 2022-06-06 at 16 49 25" src="https://user-images.githubusercontent.com/32193933/172173793-4ad6ee2a-3577-4c80-a40d-7ad8079e4cf5.png">

2022-06-06 13:49 UTC, grishbar commented on src/components/app/app.jsx
> +                )}>
`надо исправить`
    [нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html)
можешь вынести ее в компонент в useMemo или вобще в отдельный компонент, можно прямо в этом же файле

2022-06-06 13:49 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.jsx
> +                <Button type="primary" size="medium" onClick={handleClick}>
`можно лучше` 
в идеале пока в конструкторе нет ингредиентов, кнопка должна быть задизейблена

2022-06-06 13:49 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
>                      Начинки
`надо исправить` 
не надо создавать функции в jsx, пройдись пожалуйста по всему проекту и исправь это везде.
Тут можно сделать вот так:
```
                <Tab value="bun" active={current === 'bun'} onClick={scrollTo}>
                    Булки
                </Tab>
                <Tab value="sauce" active={current === 'sauce'} onClick={scrollTo}>
                    Соусы
                </Tab>
                <Tab value="main" active={current === 'main'} onClick={scrollTo}>
                    Начинки
                </Tab>
```

2022-06-06 13:49 UTC, grishbar commented on src/components/protected-route.jsx
> +export default ProtectedRoute;
`надо исправить` 
старайся по возможности не использовать if else и внутри вложенные if else (тернарники в render) такие конструкции довольно тяжело читать и еще тяжелей потом дебажить, где что отрисовалось не так, старайся логические блоки выносить  и разделять на отдельные конструкции, и тут также немного дублирования, наверное более понятно тут смогу только кодом, показать, вот, что примерно можно сделать, чтобы получилось более читаемое и масштабируемое решение:
```
const LoginRedirect = ({ location }) => (
    <Redirect to={{pathname: '/login', state: {from: location}}}/>
);

const MainPageRedirect = () => (
    <Redirect to={{pathname: '/'}}/>
);

function ProtectedRoute({isForAuthUser = false, children, ...rest}) {
    const {isAuth, isUserLoading} = useSelector(state => state.user);

    const renderComponent = useMemo(() => {
        if (isForAuthUser && !isAuth) {
            return LoginRedirect;
        }

        if (!isForAuthUser && isAuth) {
            return MainPageRedirect;
        }
        
        return () => children;
    }, [children, isAuth, isForAuthUser]);

    if (isUserLoading) {
        return <Loading/>;
    }

    return (
        <Route
            {...rest}
            render={renderComponent}
        />
    );
}
```
Также нужно у этого компонента указать propTypes

2022-06-06 13:49 UTC, grishbar commented on src/pages/forgot-password/forgot-password.jsx
> +    /** Получение данных об успешной отправки кода на email и переадресация */
`отлично` 
отличные комментарии, помогают меньше тратить времени на чтение кода

2022-06-06 13:49 UTC, grishbar commented on src/pages/forgot-password/forgot-password.jsx
> +    };
`отлично` 
крутое универсальное решение для обработки форм 👍

2022-06-06 13:49 UTC, grishbar commented on src/pages/profile/profile.jsx
> +    }
`надо исправить` 
почему пароль тут тоже не очищаешь? Вобще принято держать объект initialState и если возвращаешь к дэфолтнуому состоянию, то использовать его, а не брать все поля из формы и перезаписывать их на пустые, это как то странно. Еще если у тебя добавятся новые поля в форме то придется их дописывать в нескольких местах а не только в initialState

2022-06-06 13:49 UTC, grishbar commented on src/services/reducers/auth.js
> +        }
`надо исправить`
    При ошибке в запросе надо возвращать - initialState и isUserRequestFailed: true , так как не хочется держать в хранилище потенциально невалидные данные. И текущее решение становится тяжело масштабируемым, то есть если мы будем добавлять новые поля в форму, то придется и здесь тоже дописывать новое поле, а это во первых могут забыть и будет баг, а во вторых это лишняя работа каждый раз

2022-06-07 13:23 UTC, LemonGrace commented
Не совсем поняла комментарий по поводу выхода из профиля - я удаляю куки в файле auth.js при успешном ответе сервера, или должна быть какая-то другая логика
![logout](https://user-images.githubusercontent.com/42918083/172391070-c85faeb1-93e0-4505-b21d-4b41362c656f.gif)
?

2022-06-09 17:49 UTC, grishbar approved these changes
Великолепно, теперь рабта прекрасна, работу принмаю. Есть несколько улучшений которые ее можно сделать

- [x] При клике на “Оформить заказ” лучше будет если ты сразу будешь открывать моталку и в ней показывать лоадер пока идет post запрос
- [ ] Везде в redux пользоваться деструктурированием

2022-06-09 17:49 UTC, grishbar commented on src/pages/reset-password/reset-password.jsx
> +                    icon={'ShowIcon'}
`можно лучше` 
```
                    name="password"
                    placeholder="Введите новый пароль"
                    icon="ShowIcon"
```

2022-06-09 17:49 UTC, grishbar commented on src/services/actions/auth.js
> +            if (res && res.success) {
`можно лучше` 
кажется лучше просто проверить на res.ok , но и твое решение абсолютно корректное

2022-06-09 17:49 UTC, grishbar commented on src/services/reducers/auth.js
> +            return initialState;
`можно лучше` 
так отлично, но принято делать деструктуризацию, так, что я бы придерживался одного какого то способа создания новых копий объектов с переопределеннными свойствами в redux. То есть либо везде используешь object.Assign либо везде `{...object, someprop: somevalue}`

2022-06-10 07:03 UTC, merged